export const ApiErrorCode = {
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',

  COST_TYPE_NOT_FOUND: 'COST_TYPE_NOT_FOUND',
  COST_TYPE_ALREADY_EXISTS: 'COST_TYPE_ALREADY_EXISTS',
  COST_TYPE_HAS_ASSOCIATED_COSTS: 'COST_TYPE_HAS_ASSOCIATED_COSTS',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
