import { Product } from '../../src/products/product.entity';
import { mockCategories } from '../product-category/product-category.mock';
import { mockUsers } from '../users/users.mock';

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Playstation 5',
    purchasePrice: 200.0,
    purchaseDate: new Date('2025-01-01'),
    sold: false,
    salePrice: null,
    saleDate: null,
    user: mockUsers[0],
    category: mockCategories[0],
    attributes: [],
    costs: [],
  },
  {
    id: 2,
    name: 'T-shirt',
    purchasePrice: 10.0,
    purchaseDate: new Date('2025-01-01'),
    sold: false,
    salePrice: null,
    saleDate: null,
    user: mockUsers[1],
    category: mockCategories[1],
    attributes: [],
    costs: [],
  },
  {
    id: 3,
    name: 'Book',
    purchasePrice: 5.0,
    purchaseDate: new Date('2025-01-01'),
    sold: true,
    salePrice: 12.5,
    saleDate: new Date('2025-01-02'),
    user: mockUsers[2],
    category: mockCategories[2],
    attributes: [],
    costs: [],
  },
  {
    id: 4,
    name: 'Table',
    purchasePrice: 50.0,
    purchaseDate: new Date('2025-01-01'),
    sold: false,
    salePrice: null,
    saleDate: null,
    user: mockUsers[0],
    category: mockCategories[3],
    attributes: [],
    costs: [],
  },
  {
    id: 5,
    name: 'Chair',
    purchasePrice: 20.0,
    purchaseDate: new Date('2025-01-01'),
    sold: true,
    salePrice: 30.0,
    saleDate: new Date('2025-01-02'),
    user: mockUsers[1],
    category: mockCategories[3],
    attributes: [],
    costs: [],
  },
];
