import { ApiProperty } from '@nestjs/swagger';

export class UserStatsDto {
  @ApiProperty({
    description: 'Total costs incurred by the user.',
    example: 1500.75,
  })
  totalCosts: number;
  @ApiProperty({
    description: 'Total revenue generated by the user.',
    example: 2500.0,
  })
  totalRevenue: number;
  @ApiProperty({
    description: 'Net profit calculated as total revenue minus total costs.',
    example: 1000.25,
  })
  totalProfit: number;
  @ApiProperty({
    description: 'Percentage of profit relative to total costs.',
    example: 66.68,
  })
  totalProfitPercentage: number;
  @ApiProperty({
    description: 'Total costs associated with sold products.',
    example: 1200.5,
  })
  soldProductsCosts: number;
  @ApiProperty({
    description: 'Total revenue from sold products.',
    example: 2200.0,
  })
  soldProductsRevenue: number;
  @ApiProperty({
    description: 'Net profit from sold products.',
    example: 999.5,
  })
  soldProductsProfit: number;
  @ApiProperty({
    description: 'Profit percentage from sold products.',
    example: 83.29,
  })
  soldProductsProfitPercentage: number;
  @ApiProperty({
    description: 'Total number of products associated with the user.',
    example: 50,
  })
  numberOfProducts: number;
  @ApiProperty({
    description: 'Number of products sold by the user.',
    example: 30,
  })
  numberOfSoldProducts: number;
  @ApiProperty({
    description: 'Time period for which the statistics are calculated.',
    example: 'Q1 2025',
  })
  period: string;
}
